const express = require('express')
const router = express.Router()

const question = require('./question')
const answer = require('./answer')
const majors = require('./majors')
const professions = require('./professions')
const auth = require('./auth')
const user = require('./user')
const master = require('./master')
const materials = require('./materials')
const tests = require('./tests')
const counseling = require('./counseling')
const dashboard = require('./dashboard')
const settings = require('./settings')
const chat = require('./chat')

const { verifyToken } = require('../middlewares/auth')

router.use('/auth', auth)
router.use('/user', verifyToken, user)
router.use('/question', verifyToken, question)
router.use('/answer', verifyToken, answer)
router.use('/majors', verifyToken, majors)
router.use('/professions', verifyToken, professions)
router.use('/master', verifyToken, master)
router.use('/materials', verifyToken, materials)
router.use('/tests', verifyToken, tests)
router.use('/counseling', verifyToken, counseling)
router.use('/dashboard', verifyToken, dashboard)
router.use('/setting', verifyToken, settings)
router.use('/chat', verifyToken, chat)

module.exports = router
